---
title: "homework 5"
author: "Maelle Coupannec"
date: "17/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LOADING LIBRARY

We are loading some library to clean the data and create the map.

```{r load library}
library(tidyverse)
library(forcats)
library(tigris)
library(viridis)
library(sf)
library(ggthemes)


```
```{r}
homicides <- read_csv("../data/homicide-data.csv")

homicides <- homicides %>%
  unite(col = city_name, c(city, state), sep=", ") %>%
  filter(city_name=="Las Vegas, NV") %>% 
  mutate(victim_race= fct_lump(victim_race, n=3)) %>% 
  filter(!is.na(lon)|!is.na(lon)) %>% 
  filter(victim_race!="Other") %>%
  mutate(disposition=fct_recode(disposition,
                                solved = "Closed by arrest",
                                unsolved = "Closed without arrest", 
                                unsolved ="Open/No arrest"))
  

head(homicides)
```

We filtered the data frame to keep only the homicides in Las Vegas.


```{r}
map_lv <- block_groups( state="NV", county = "Clark county", 
                  year = NULL, class="sf")


ggplot()+
  geom_sf(data = map_lv, color = "black", 
          alpha = 0.1, size = 0.1)+
  geom_point(data = homicides, 
             aes(x = lon, y = lat, 
                shape = disposition, 
                color = victim_race), size = 0.8) +
  ggtitle("Homicides in Las Vegas, Nevada",
          subtitle = "Solved and unsolved casses by race")+
  labs(x = "", y = "", shape= "case status", 
       color= "race of the victim")

```


```{r}
ggplot()+
  geom_sf(data = map_lv, color = "pink", 
          alpha = 0.1, size = 0.1)+
  geom_point(data = homicides, 
             aes(x = lon, y = lat, 
                shape = disposition, 
                color = victim_race), size = 0.8)+
  xlim(c(-115.4, -114.8)) + ylim(c(35.9, 36.4))+
  ggtitle("Homicides in Las Vegas, Nevada",
          subtitle = "Solved and unsolved casses by race")+
  theme_few() + 
  labs(x = "", y = "", shape= "case status", 
       color= "race of the victim")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
  
```

